# Generated by Django 3.1.5 on 2021-09-13 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'AppUserCourse',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=16)),
                ('program', models.TextField()),
                ('points', models.IntegerField()),
                ('regularSemester', models.IntegerField()),
                ('irregularSemester', models.IntegerField()),
                ('optional', models.BooleanField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='upisi',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='upisi',
            name='student',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='status',
        ),
        migrations.AddField(
            model_name='appuser',
            name='isIrregular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='appuser',
            table='AppUser',
        ),
        migrations.DeleteModel(
            name='Predmeti',
        ),
        migrations.DeleteModel(
            name='Upisi',
        ),
        migrations.AddField(
            model_name='appusercourse',
            name='appUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appusercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.course'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.role'),
        ),
    ]
